dist: trusty
sudo: required
language: csharp
mono: none
dotnet: "2.0.0"
solution: test-repo.sln
# env:
#  matrix:
#   - SH=bash
#   - PACKAGE_VERSION="1.0.0"
install:
 - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script: 
  - sudo nuget.exe update -Self
  - "dotnet restore"
  - "dotnet build -c Release --no-restore"
deploy:

  skip_cleanup: true
  provider: script
  script:
  - mono nuget.exe pack ./test-repo.nuspec -Verbosity detailed -Version 1.0.0
#  - mono nuget.exe push ./test-repo.*.nupkg -Verbosity detailed -ApiKey=$NUGET_SOURCE -Source=$PACKAGE_VERSION
  on: 
    branch: master
after_deploy: 
  - "git config --global user.email \"builds@travis-ci.com\""
  - "git config --global user.name \"Travis CI\""
  - "export GIT_TAG=$1.0.0"
  - "git tag $GIT_TAG -a -m \"Generated tag $GIT_TAG from TravisCI build $TRAVIS_BUILD_NUMBER\""
  - "git push --quiet https://$GITHUBKEY@github.com/gdyrrahitis/test-repo $GIT_TAG"
